In [1]:
BASE_URL = "https://blockchain-team-badass.herokuapp.com"
PARKING_SPOT_URL = BASE_URL + "/parkingspots/"
STATE = BASE_URL + "/state/"

In [3]:
import pandas

data = pandas.read_csv("raw_data.csv")

In [4]:
data.head()

,parking_spot_id,car_present,coordinate_tag_x,coordinate_tag_y,start_time_stamp,end_time_stamp,time_int
0,552b6,True,32.751453,-105.498265,03/03/18_13:49,03/03/18_14:06,0:17
1,s3d8f,False,33.360416,-105.667375,03/03/18_13:48,03/03/18_14:21,0:33
2,d61fc,False,35.119482,-103.822230,03/03/18_13:17,03/03/18_14:04,0:47
3,598b1,False,35.878428,-103.323142,03/03/18_13:20,03/03/18_14:43,1:23
4,e9cb7,True,35.142305,-103.148376,03/03/18_13:04,03/03/18_14:10,1:06

In [24]:
unique_parking_spots = data.drop_duplicates(subset="parking_spot_id")
unique_parking_spots

,parking_spot_id,car_present,coordinate_tag_x,coordinate_tag_y,start_time_stamp,end_time_stamp,time_int
0,552b6,True,32.751453,-105.498265,03/03/18_13:49,03/03/18_14:06,0:17
1,s3d8f,False,33.360416,-105.667375,03/03/18_13:48,03/03/18_14:21,0:33
2,d61fc,False,35.119482,-103.822230,03/03/18_13:17,03/03/18_14:04,0:47
3,598b1,False,35.878428,-103.323142,03/03/18_13:20,03/03/18_14:43,1:23
4,e9cb7,True,35.142305,-103.148376,03/03/18_13:04,03/03/18_14:10,1:06
5,9s6ec,False,36.767287,-103.999599,03/03/18_13:09,03/03/18_14:36,1:27
6,5fa15,False,36.311760,-103.326817,03/03/18_13:14,03/03/18_14:04,0:50
7,498fa,True,35.285771,-104.194698,03/03/18_13:57,03/03/18_14:39,0:42
8,3a8a8,True,35.059210,-104.376625,03/03/18_13:15,03/03/18_14:14,0:59
9,71d33,False,36.725861,-103.684739,03/03/18_13:08,03/03/18_14:36,1:28
10,576ec,True,36.899379,-103.541874,03/03/18_13:21,03/03/18_14:31,1:10
11,cb9e3,False,35.298352,-104.481343,03/03/18_13:08,03/03/18_14:21,1:13
12,376d6,True,36.345307,-103.991534,03/03/18_13:05,03/03/18_14:53,1:48
13,516f0,False,36.412538,-103.656438,03/03/18_13:34,03/03/18_14:34,1:00
14,da12b,True,35.543561,-103.508304,03/03/18_13:37,03/03/18_14:23,0:46
15,e9cb8,False,34.770502,-103.774375,03/03/18_13:20,03/03/18_14:32,1:12
16,5fd14,True,35.581906,-103.179169,03/03/18_13:51,03/03/18_14:19,0:28
17,81c5f,True,35.170055,-104.274806,03/03/18_13:25,03/03/18_14:59,1:34
18,3b12f,False,35.152021,-103.303690,03/03/18_13:16,03/03/18_14:03,0:47
19,d0508,False,34.914545,-104.695340,03/03/18_13:26,03/03/18_14:55,1:29
20,d52ea,True,36.137283,-103.123139,03/03/18_13:48,03/03/18_14:21,0:33
21,4ddi3,False,37.276925,-115.394121,03/03/18_13:53,03/03/18_14:33,0:40
22,539ef,True,35.998367,-114.960947,03/03/18_13:05,03/03/18_14:33,1:28
23,222b9,True,36.971364,-116.744158,03/03/18_13:50,03/03/18_14:56,1:06
24,07f0e,False,36.102863,-115.487115,03/03/18_13:10,03/03/18_14:11,1:01
25,492ef,False,35.986677,-114.809401,03/03/18_13:28,03/03/18_14:20,0:52
26,e656c,True,36.666657,-114.226747,03/03/18_13:08,03/03/18_14:41,1:33
27,3d523,False,37.286087,-114.513105,03/03/18_13:33,03/03/18_14:52,1:19
28,402b6,True,37.782535,-118.074900,03/03/18_13:04,03/03/18_14:53,1:49
29,453a3,False,36.074719,-114.985309,03/03/18_13:42,03/03/18_14:18,0:36
...,...,...,...,...,...,...,...
69,ac63d,False,36.151382,-115.108648,03/03/18_13:28,03/03/18_14:58,1:30
70,6479d,False,36.181706,-115.163231,03/03/18_13:34,03/03/18_14:42,1:08
71,9b00e,False,36.171241,-115.209288,03/03/18_13:29,03/03/18_14:07,0:38
72,634f2,False,36.205256,-115.223639,03/03/18_13:25,03/03/18_14:22,0:57
73,1f2c7,True,36.131720,-115.168382,03/03/18_13:10,03/03/18_14:21,1:11
74,95be4,True,36.171429,-115.047734,03/03/18_13:06,03/03/18_14:21,1:15
75,37c9d,False,36.061152,-115.263515,03/03/18_13:41,03/03/18_14:58,1:17
76,8ea43,False,36.253640,-115.041052,03/03/18_13:25,03/03/18_14:07,0:42
77,0656e,False,36.140961,-115.281091,03/03/18_13:15,03/03/18_14:01,0:46
78,b8d7d,True,36.077380,-115.213966,03/03/18_13:12,03/03/18_14:14,1:02
79,9453a,True,36.084721,-115.146129,03/03/18_13:19,03/03/18_14:51,1:32
80,a7422,True,36.081318,-115.095455,03/03/18_13:31,03/03/18_14:01,0:30
81,9256s,False,36.121526,-115.091277,03/03/18_13:05,03/03/18_14:40,1:35
82,60bb0,True,36.106432,-115.040286,03/03/18_13:07,03/03/18_14:14,1:07
83,a2c00,True,36.035206,-115.148789,03/03/18_13:56,03/03/18_14:04,0:08
84,5ws25,True,36.114842,-115.613219,03/03/18_13:18,03/03/18_14:12,0:54
85,a39f1,False,36.196814,-115.264363,03/03/18_13:55,03/03/18_14:30,0:35
86,4cd75,True,36.233315,-115.290150,03/03/18_13:24,03/03/18_14:01,0:37
87,5276a,True,36.253975,-115.227105,03/03/18_13:06,03/03/18_14:53,1:47
88,2f2iw,True,36.309668,-115.249674,03/03/18_13:45,03/03/18_14:44,0:59
89,7a4d1,False,36.202733,-115.307750,03/03/18_13:56,03/03/18_14:32,0:36
90,22b8d,False,36.100973,-115.375908,03/03/18_13:41,03/03/18_14:07,0:26
91,950cf,True,36.166612,-115.361275,03/03/18_13:43,03/03/18_14:01,0:18
92,dd71f,True,36.034661,-115.211656,03/03/18_13:55,03/03/18_14:28,0:33
93,4ce02,False,35.988424,-115.207059,03/03/18_13:47,03/03/18_14:29,0:42
94,1f1ba,True,36.147922,-115.036367,03/03/18_13:50,03/03/18_14:50,1:00
95,09d18,True,36.322319,-115.293151,03/03/18_13:49,03/03/18_14:05,0:16
96,c8f06,False,36.178886,-115.320759,03/03/18_13:50,03/03/18_14:59,1:09
97,e9d62,False,36.167690,-115.277862,03/03/18_13:57,03/03/18_14:50,0:53
98,6f893,True,36.143249,-115.226909,03/03/18_13:55,03/03/18_14:00,0:05